# Pinagbabaan ng Gradle version para tugma sa Expo SDK 52
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
# Iwas sa error na "serviceOf" — hindi tugma ang bagong Gradle
systemProp.org.gradle.internal.configurationcache.enabled=false
