# Tamang Gradle version para sa Expo SDK 52 / React Native 0.74
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true

# Iwas sa configuration cache na nagdudulot ng serviceOf error
org.gradle.configuration-cache.enabled=false
